"""Printable internal reference PDFs (replaces Word templates in the catalog)."""

from __future__ import annotations

from io import BytesIO
from typing import Any, Optional

from pypdf import PdfWriter
from pypdf.generic import DictionaryObject, NameObject, StreamObject


def _esc_pdf_text(s: str) -> bytes:
    t = (
        (s or "")
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
        .replace("\r", " ")
        .replace("\n", " ")
    )
    return t.encode("utf-8")


def _s(v: Any) -> str:
    if v is None:
        return ""
    return str(v).strip()


def internal_form_reference_pdf_bytes(
    title: str,
    *,
    form_id: str,
    locale: str,
    worker: Optional[dict] = None,
    org_name: str = "",
    org_address: str = "",
) -> bytes:
    """
    Letter-size reference page: form title, worker snapshot, employer line, usage note.
    Not a government form — for filing/policy packets only.
    """
    title = (title or form_id or "Internal form").strip()
    loc = (locale or "en").strip()
    w = worker or {}
    nm = " ".join([_s(w.get("first_name")), _s(w.get("last_name"))]).strip() or "—"
    lines: list[str] = [
        f"Reference packet: {form_id}  ·  Locale: {loc}",
        "",
        "Worker (from payroll record)",
        f"  Name: {nm}",
        f"  Email: {_s(w.get('email')) or '—'}",
        f"  Mobile: {_s(w.get('mobile')) or '—'}",
        f"  Employee ID: {_s(w.get('employee_id')) or '—'}",
        f"  Mailing address: {_s(w.get('address')).replace(chr(10), ' / ')[:220] or '—'}",
        "",
        "Employer (from Organization settings)",
        f"  {_s(org_name) or '—'}",
        f"  {_s(org_address)[:200] or ''}".strip() or "  —",
        "",
        "This PDF is generated by the app as an internal reference.",
        "Complete, sign, and retain per your policy; replace with your final template if required.",
    ]

    w_pdf = PdfWriter()
    w_pdf.add_blank_page(width=612, height=792)
    page = w_pdf.pages[0]
    ops_parts: list[bytes] = []
    ops_parts.append(b"BT /F1 14 Tf 72 740 Td (" + _esc_pdf_text(title) + b") Tj ET")
    y = 712
    for line in lines:
        sz = 9 if line.startswith("  ") else 10
        if line == "":
            y -= 6
            continue
        ops_parts.append(b"BT /F1 %d Tf 72 %d Td (" % (sz, y) + _esc_pdf_text(line) + b") Tj ET")
        y -= max(12, sz + 2)
        if y < 56:
            break
    stream = b"\n".join(ops_parts)
    content = StreamObject()
    content._data = stream
    content.update({NameObject("/Length"): len(stream)})
    page[NameObject("/Resources")] = DictionaryObject(
        {
            NameObject("/Font"): DictionaryObject(
                {
                    NameObject("/F1"): DictionaryObject(
                        {
                            NameObject("/Type"): NameObject("/Font"),
                            NameObject("/Subtype"): NameObject("/Type1"),
                            NameObject("/BaseFont"): NameObject("/Helvetica"),
                        }
                    ),
                }
            ),
        }
    )
    page[NameObject("/Contents")] = w_pdf._add_object(content)
    buf = BytesIO()
    w_pdf.write(buf)
    return buf.getvalue()
