-- Management Issues Phase 1 — internal quality / claims (not WF Review).
-- INTERNAL mgmt_issues != future Rinse-published issues projection.

CREATE TABLE IF NOT EXISTS mgmt_issue_taxonomy (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT NOT NULL,
  kind VARCHAR(16) NOT NULL,
  code VARCHAR(64) NOT NULL,
  parent_category_code VARCHAR(64) NULL,
  label VARCHAR(128) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  maps_from_external_type VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_mgmt_issue_tax_org_kind_code (organization_id, kind, code),
  KEY idx_mgmt_issue_tax_org_kind_active (organization_id, kind, active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mgmt_issues (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT NOT NULL,
  matched_state VARCHAR(16) NOT NULL,
  bag_id VARCHAR(64) NULL,
  order_instance_id BIGINT NULL,
  manual_identifier VARCHAR(255) NULL,
  unmatched_reason VARCHAR(512) NULL,
  customer_name_snapshot VARCHAR(255) NULL,
  service_type_snapshot VARCHAR(16) NULL,
  rush_snapshot TINYINT(1) NULL,
  production_date_et DATE NULL,
  completed_at_et DATETIME NULL,
  issue_category VARCHAR(64) NOT NULL,
  issue_subtype VARCHAR(64) NOT NULL,
  reported_at_et DATETIME NOT NULL,
  description TEXT NULL,
  internal_notes TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  severity VARCHAR(32) NULL,
  resolution_type VARCHAR(64) NULL,
  resolution_notes TEXT NULL,
  resolved_at_et DATETIME NULL,
  claim_amount DECIMAL(12,2) NULL,
  vendor_percentage DECIMAL(6,2) NULL,
  final_vendor_claim DECIMAL(12,2) NULL,
  external_issue_id VARCHAR(128) NULL,
  external_issue_url VARCHAR(512) NULL,
  external_type VARCHAR(64) NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'manual',
  created_by_user_id INT NULL,
  created_by_name VARCHAR(255) NULL,
  updated_by_user_id INT NULL,
  updated_by_name VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_mgmt_issues_org_bag (organization_id, bag_id),
  KEY idx_mgmt_issues_org_oi (organization_id, order_instance_id),
  KEY idx_mgmt_issues_org_prod_cat (organization_id, production_date_et, issue_category),
  KEY idx_mgmt_issues_org_reported (organization_id, reported_at_et),
  KEY idx_mgmt_issues_org_status_prod (organization_id, status, production_date_et),
  UNIQUE KEY uq_mgmt_issues_org_external (organization_id, external_issue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mgmt_issue_attributions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  issue_id BIGINT NOT NULL,
  organization_id INT NOT NULL,
  employee_user_id INT NULL,
  employee_name_snapshot VARCHAR(255) NULL,
  role_key VARCHAR(32) NOT NULL,
  stage_key VARCHAR(32) NOT NULL,
  attribution_source VARCHAR(64) NOT NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'none',
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  is_manager_override TINYINT(1) NOT NULL DEFAULT 0,
  is_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  is_not_applicable TINYINT(1) NOT NULL DEFAULT 0,
  original_employee_user_id INT NULL,
  original_employee_name VARCHAR(255) NULL,
  original_role_key VARCHAR(32) NULL,
  original_stage_key VARCHAR(32) NULL,
  override_reason VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id INT NULL,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by_user_id INT NULL,
  KEY idx_mgmt_attr_issue (issue_id),
  KEY idx_mgmt_attr_org_emp_role (organization_id, employee_user_id, role_key),
  KEY idx_mgmt_attr_org_role (organization_id, role_key, is_primary)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mgmt_issue_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  issue_id BIGINT NOT NULL,
  organization_id INT NOT NULL,
  action VARCHAR(64) NOT NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  reason VARCHAR(512) NULL,
  actor_user_id INT NULL,
  actor_display_name VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_mgmt_issue_ev_issue (issue_id, created_at),
  KEY idx_mgmt_issue_ev_org_created (organization_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
