-- Folding performance per completed bag (FOLDING → CLEAN interval).
CREATE TABLE IF NOT EXISTS rinse_folding_performance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_id INT NOT NULL,
  bag_id VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'EXCEPTION',
  exception_code VARCHAR(64) NULL,
  folding_start_at DATETIME NULL,
  folding_end_at DATETIME NULL,
  duration_seconds INT NULL,
  folding_start_event_id INT NULL,
  folding_end_event_id INT NULL,
  folding_start_rack VARCHAR(128) NULL,
  folding_end_rack VARCHAR(128) NULL,
  assigned_user_name VARCHAR(255) NULL,
  assigned_user_name_source VARCHAR(32) NULL,
  employee_id INT NULL,
  weight_lbs DECIMAL(8,2) NULL,
  work_date DATE NULL,
  registry_completion_status VARCHAR(24) NULL,
  excluded_from_performance TINYINT(1) NOT NULL DEFAULT 0,
  admin_notes TEXT NULL,
  folding_scan_count INT NULL,
  clean_scan_count INT NULL,
  source_recompute_kind VARCHAR(32) NULL,
  computed_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rfp_org_bag (organization_id, bag_id),
  KEY idx_rfp_org_work_date (organization_id, work_date),
  KEY idx_rfp_org_user_date (organization_id, assigned_user_name, work_date),
  KEY idx_rfp_org_status (organization_id, status, exception_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
