export const DEFAULT_INPUTS = {
  start_time: "7:00 AM",
  target_time: "12:00 PM",
  bag_count: 50,
  avg_lbs_per_bag: 20,
  orders_using_2_washers: 40,
  orders_using_2_dryers: 10,
  washer_count: 4,
  dryer_count: 4,
  wash_cycle_min: 30,
  dry_cycle_min: 45,
  weigh_min_per_bag: 1,
  sort_min_per_bag: 5,
  fold_min_per_bag: 6,
  folder_count: 3,
  sorter_count: 1,
  weigher_count: 1,
  washer_person_count: 1,
  batch_size: 8,
  helper_rule: "none",
  weighing_handled_by: "dedicated_weigher",
  weighing_mode: "separate_lane",
  washing_strategy: "batch_washing",
  load_washer_min: 3,
  unload_washer_min: 3,
  load_dryer_min: 3,
  unload_dryer_min: 2,
  washer_transfer_min: 5,
  batch_overrides: [],
  strategy_flags: [],
};

export const STRATEGY_FLAGS = [
  { key: "continuous_sorting", label: "Continuous sorting" },
  { key: "weigh_all_first", label: "Weigh all first" },
  { key: "batch_washing", label: "Batch washing" },
  { key: "sorter_helps_washer", label: "Sorter can help washer" },
  { key: "washer_helps_folding", label: "Washer helps folding when idle" },
  { key: "sorter_helps_if_surplus", label: "Sorter helps when surplus ≥ 1 batch" },
  { key: "prioritize_folded", label: "Prioritize folded by target" },
  { key: "prioritize_ready", label: "Prioritize ready by target" },
];

export const HELPER_ASSIGN_OPTIONS = [
  { value: "none", label: "None" },
  { value: "sorter", label: "Sorter → washer transfer" },
  { value: "folder", label: "Folder → washer transfer" },
  { value: "extra_washer", label: "+1 washer helper" },
];
